name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build-Typecheck-Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.13.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run lint
        run: pnpm lint

      - name: Build
        run: pnpm build
